# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlrequest',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
